services:
#  api-gateway:
#    image: api-gateway
#    build:
#      context: .
#      dockerfile: api-gateway/Dockerfile
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: my-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
